/**
 * Script utilities for javascript and templater scripts in Obsidian
 * 
 * @author Ljavuras <ljavuras.py@gmail.com>
 */

class Script {

    /**
     * Returns a Script object with relavent info
     * @param {TFile} file - Script file
     * @returns {this.Script}
     */
    get(file) {
        return new this.Script(file);
    }

    getByPath(path) {
        const file = app.vault.getAbstractFileByPath(path);
        if (file) {
            return this.get(file);
        }
    }

    template = {
        /**
         * Insert template info into target file
         * @param {Object} tp - Templater current functions object
         */
        setInfo(tp) {
            tp = customJS.Templater.wrap(tp);
            let template_name = tp.config.template_file.basename;
            customJS.Script.get(tp.config.template_file).getVersion()
                .then((version) => {
                    tp.setFrontMatter({
                        'template/name'   : `[[${template_name}]]`,
                        'template/version': version,
                    });
                });
        },

        /**
         * Updates version number of target file
         * @param {Object} tp - Templater current functions object
         * @param {number} version - Updated version number
         */
        setVersion(tp, version) {
            tp = customJS.Templater.wrap(tp);
            tp.setFrontMatter({
                'template/version': version,
            });
        },

        /**
         * Gets template info of a note
         * @param {TFile} file - Note file
         * @returns {Object} templateInfo - Info of the template the note is generated from
         * @returns {string} templateInfo.name - Template name
         * @returns {number} templateInfo.version - Template version
         */
        getInfo(file) {
            let frontmatter = customJS.Obsidian.frontmatter.get(file);

            return {
                name: frontmatter?.['template/name'].slice(2, -2),
                version: frontmatter?.['template/version']
            };
        }
    }

    Script = class {
        /**
         * @param {TFile} file - Script file
         */
        constructor(file) {
            this.file = file;
        }

        get name() {
            return this.file.basename;
        }

        async getContent() {
            if (!this._content) {
                this._content = await app.vault.cachedRead(this.file);
            }
            return this._content;
        }

        async getVersion() {
            let version = (await this.getContent())
                .match(/\/\*[\s\S]*?@version\s+(?<version>\d+)[\s\S]*?\*\//)
                ?.groups.version;
            if (version) { version = Number(version); }
            return version ?? '';
        }

        async getExcerpt() {
            return (await this.getContent())
                .match(/\/\*[\s\*]*(?<excerpt>.*)\b[\s\S]*?\*\//)?.groups.excerpt
                ?? '';
        }

        /**
         * Get all notes generated by this template
         * @returns {DataArray<SMarkdownPage>}
         */
        getNotes() {
            return DataviewAPI.pages(`[[${this.name}]]`)
                .filter((page) => {
                    return page['template/name']?.path == this.file.path;
                })
                .sort(p => p.file.name);
        }
    }
}