/**
 * Template manager
 * 
 * Features
 * - List all templates
 * - Display template excerpt
 * - List/update notes generated by each template
 * 
 * Required plugins
 * - Dataview
 * - Templater
 * - CustomJS
 * 
 * Use Dataview custom view `dv.view()` to run this script
 * 
 * @author Ljavuras <ljavuras.py@gmail.com>
 */

const { Obsidian, obsidian, Script, Dataview, Templater, Violet } = await cJS();
const containerEl = input?.containerEl ?? dv.container;

await Dataview.importStyle(dv, "System/script/Dataview/common.css");

/**
 * Template information for each templates
 * - Template name
 * - Template status
 * - Notes generated by each template
 */
class templateInfo {
    /**
     * @param {customJS.Script.Script} template
     */
    constructor(template) {
        this.containerEl = createFragment().createDiv("templates__template");
        this.infoEl = this.containerEl.createDiv("templates__template-header");
        this.infoEl.createDiv("templates__template-name").setText(template.name);
        this.infoEl.onclick = () => {
            this.containerEl.toggleClass("active", !this.containerEl.hasClass("active"));
            this.details.toggle();
        }
        this.notes = template.getNotes();

        /**
         * Template status
         * - Update available indicator
         * - Missing updater indicator
         * - Note count
         */
        if (this.notes.length) {
            template.getVersion().then((version) => {
                this.version = version;

                // Update available indicator
                if (this.notes.some((page) => {
                    return Templater.exists(
                        `${template.name}.update.${page['template/version']}`
                    );
                })) {
                    let iconDiv = this.infoEl.createDiv(
                        "icon-wrap templates__template-status update-available"
                    );
                    obsidian.setIcon(iconDiv, 'arrow-up-circle');
                    obsidian.setTooltip(iconDiv, "Update available");
                }

                // Missing updater indictor
                if (this.notes.some((page) => {
                return typeof page['template/version'] === 'number'
                    && page['template/version'] < version
                    && !Templater.exists(
                        `${template.name}.update.${page['template/version']}`
                    );
                })) {
                    let iconDiv = this.infoEl.createDiv(
                        "icon-wrap templates__template-status missing-updater"
                    );
                    obsidian.setIcon(iconDiv, 'alert-triangle');
                    obsidian.setTooltip(iconDiv, "Missing updater");
                }

                // Note count
                this.infoEl.createDiv().setText(this.notes.length);
            })
        }

        /**
         * - Number of latest, update available and missing updater notes
         * - Template excerpt
         * - Notes generated by this template
         */
        this.details = {
            templateInfo: this,
            _init: async function(containerEl) {
                /**
                 * Filter through notes in two pass
                 * - Create outdatedNotes and updatableNotes
                 * - Generate page['template/status']
                 */
                let outdatedNotes = this.templateInfo.notes.filter((page) => {
                    let noteVersion = page['template/version'];
                    let isOutdated = typeof noteVersion === 'number'
                        && noteVersion < this.templateInfo.version;

                    page['template/status'] = isOutdated? "missing-updater" : "latest";

                    return isOutdated;
                });

                let updatableNotes = outdatedNotes.filter((page) => {
                    let isUpdatable = Templater.exists(
                        `${template.name}.update.${page['template/version']}`
                    );

                    if (isUpdatable) { page['template/status'] = "update-available"; }
                    return isUpdatable;
                })

                this.el = containerEl.createDiv("templates__template-details");

                /**
                 * Latest, update available, missing updater progress bar
                 */
                if (this.templateInfo.notes.length) {
                    let progressEl = this.el.createDiv("templates__progress");
                    let progressLegendEl = this.el.createEl("ul", { cls: "templates__progress-legends" });
                    let totalNoteCount = this.templateInfo.notes.length;
                    let latestNoteCount = totalNoteCount - outdatedNotes.length;
                    let canUpdateNoteCount = updatableNotes.length;
                    let missingUpdaterNoteCount = outdatedNotes.length - canUpdateNoteCount;
                    if (latestNoteCount) {
                        progressEl.createSpan({
                            cls: "templates__progress-item latest",
                            attr: {
                                style: `width: ${(latestNoteCount/totalNoteCount)*100}%;`
                            }
                        });
                        let legendEl = progressLegendEl.createEl("li", { cls: "templates__progress-legend latest" });
                        legendEl.createSpan({cls: "templates__progress-legend-title", text: "Latest"});
                        legendEl.createSpan({cls: "templates__progress-legend-count", text: `${latestNoteCount}`})
                    }
                    if (canUpdateNoteCount) {
                        progressEl.createSpan({
                            cls: "templates__progress-item update-available",
                            attr: {
                                style: `width: ${(canUpdateNoteCount/totalNoteCount)*100}%`
                            }
                        });
                        let legendEl = progressLegendEl.createEl("li", { cls: "templates__progress-legend update-available" });
                        legendEl.createSpan({cls: "templates__progress-legend-title", text: "Update available"});
                        legendEl.createSpan({cls: "templates__progress-legend-count", text: `${canUpdateNoteCount}`})
                    }
                    if (missingUpdaterNoteCount) {
                        progressEl.createSpan({
                            cls: "templates__progress-item missing-updater",
                            attr: {
                                style: `width: ${(missingUpdaterNoteCount/totalNoteCount)*100}%`
                            }
                        });
                        let legendEl = progressLegendEl.createEl("li", { cls: "templates__progress-legend missing-updater" });
                        legendEl.createSpan({cls: "templates__progress-legend-title", text: "Missing updater"});
                        legendEl.createSpan({cls: "templates__progress-legend-count", text: `${missingUpdaterNoteCount}`})
                    }
                }

                /**
                 * Details header
                 * - Template excerpt
                 * - Update all button
                 */
                this.headerEl = this.el.createDiv("templates__template-details__header");
                let excerptEl = this.headerEl.createDiv("templates__template-details__excerpt");
                template.getExcerpt().then((excerpt) => {
                    excerptEl.setText(excerpt)
                });

                let updateAllBtn = this.headerEl.createEl("button", {
                    cls: "mod-cta",
                    text: "Update all",
                });
                updateAllBtn.onclick = async () => {
                    let updateNotice = new Notice("", 0);
                    updateNotice.noticeEl.addClass("is-loading");
                    for (let [index, note] of updatableNotes.array().entries()) {
                        updateNotice.setMessage(
                            `Updating notes (${index+1}/${updatableNotes.length})` + '\n'
                            + `for template ${template.name}` + '\n'
                            + `${note.file.name}`
                        );
                        await Templater.update(Dataview.getFile(note));
                    }
                    setTimeout(() => { updateNotice.hide() }, 4000);
                    new Notice(`${updatableNotes.length} notes updated for template ${template.name}`);
                }

                /**
                 * List of notes generated by this template
                 */
                this.noteListEl = this.el.createDiv("templates__notes");
                for (let note of this.templateInfo.notes) {
                    let noteEl = new Obsidian.Link(
                        Dataview.getFile(note),
                        dv.currentFilePath
                    ).toAnchor(true);
                    noteEl.addClass("templates__note");
                    this.noteListEl.appendChild(noteEl);
                    noteEl.createSpan({
                        cls: "templates__note-title",
                        text: note.file.name
                    });
                    noteEl.createSpan({
                        text: `${note['template/version']}`
                    });

                    let updateButton = noteEl.createDiv()
                        .createEl("button", { cls: "templates__note-update-btn" });
                    switch (note['template/status']) {
                        case "update-available":
                            updateButton.setText("Update");
                            updateButton.onclick = (event) => {
                                // Stops noteEl's onclick to activate,
                                // which will open the note (noteEl is an anchor)
                                event.stopPropagation();
                                new Notice(`Updating note ${note.file.name}`);
                                Templater.update(Dataview.getFile(note))
                                    .then(() => {
                                        new Notice(`Note ${note.file.name} updated`);
                                    })
                            }
                            updateButton.onmouseover = (event) => {
                                // Stops note preview when mouseenters button
                                event.stopPropagation();
                            }
                            break;
                        case "missing-updater":
                            updateButton.setText("No updater");
                            updateButton.disabled = true;
                            break;
                        case "latest":
                            updateButton.setText("Up to date");
                            updateButton.disabled = true;
                            break;
                    }
                }

                if (updatableNotes.length == 0) {
                    updateAllBtn.disabled = true;
                }
            },

            /**
             * Show/hide template details
             * 
             * Lazy initalize details.
             */
            toggle: async () => {
                if (!this.details.el) {
                    await this.details._init(this.containerEl);
                } else {
                    this.details.el.toggle(!this.details.el.isShown());
                }
            },
        }

        return this.containerEl;
    }
}

const templateFolder = app.plugins.plugins["templater-obsidian"].settings.templates_folder;
let templates = Violet.require("violet-templater")
    .Templater.getUserTemplates()
    .map(item => Script.getByPath(item.file.path));

containerEl.createDiv({ text: `Template location: ${templateFolder}` });
let templateListEl = containerEl.createDiv("templates__templates-container");

for (let template of templates) {
    templateListEl.appendChild(new templateInfo(template));
}